### ISSUE TITLE
Unable to run both the hello_there and hello_there_task functions when running on single flask server

### ISSUE THREAD

**Issue by PhoduCoder** [rlucioni/hello-there#1]
I used your sample code here and am running it on a flask server.
The issue is "hello_there" function is not getting executed(when a custom slack command is called) and hence a timeout is observed after invoking the custom slash command.
This is because as soon as custom command is fired,
the control is passed to hello_there_task, which has a sleep of 5 seconds.

Can you advise on how to circumvent this.
Do you suggest using threading or multi processing?

**Comment by rlucioni** [comment]
The task with the sleep is for illustrative purposes, meant to accompany https://renzo.lucioni.xyz/serverless-slash-commands-with-python/. Specifically:

> The `@task` decorator tells Zappa to run `hello_there_task()` asynchronously as a separate, one-off Lambda function. As a result, `hello_there_task()` should return immediately in spite of the blocking, 5-second sleep. When run locally, the task will execute synchronously.

If you want to see it working as intended, you need to deploy to Lambda.
